package bill;


import DBConnect.DBconnect;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class creditSales extends javax.swing.JFrame {
     private DefaultTableModel model;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    /**
     * Creates new form creditSales
     */
    public creditSales() {
        con = DBconnect.connect();
        initComponents();
        showDate();
         showTime();
    }
    
     public void tableload()
     {
     try
     {
     String sql= "SELECT Item_ID,Item_Name,QTY,DiscountsP,Net_Amount FROM creditsales";
     pst = con.prepareStatement(sql);
     rs = pst.executeQuery();
          mod=new DefaultTableModel();  
     jTable1.setModel(DbUtils.resultSetToTableModel(rs));
     }
        
     catch(Exception e)
     {
        
     }
     
     
    
     }
     
     void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        jLabel17.setText(s.format(d));

    }

    void showTime() {
       new Timer(0, new ActionListener() {

           @Override
           public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("HH:mm:ss");
                jLabel16.setText(s.format(d));
            }

        }
        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 999, 364));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Invoice ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Item Code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 63, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Item Name ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("MRP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 101, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Discount Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DiccountP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 101, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 63, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 100, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 90, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, 20));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 90, 20));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 90, 20));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 60, 90, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Time");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 50, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Date");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, 70, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("NetAmount");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 220, 110, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Payed");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 330, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 590, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("0.00");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 590, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Cash");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 630, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 630, 90, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Balance");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 670, -1, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 670, 90, -1));

        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 440, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        DefaultTableModel mod;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        mod=new DefaultTableModel();
        jTable1.setModel(mod);
        
        mod.addColumn("Item Code");
        mod.addColumn("Item Name");
        mod.addColumn("Quantity");
        mod.addColumn("Discount");
        mod.addColumn("Net Amount");
    }//GEN-LAST:event_formWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        Float saleAmount1;
        Float quty1;
        Float discount1;
        Float discunt;
        
        Pay1 p = new Pay1();
        p.setSaleAmount1(Float.parseFloat(jLabel10.getText()));
        p.setDiscount1(Float.parseFloat(jTextField4.getText()));
        p.setQuty1(Float.parseFloat(jTextField5.getText()));
        
         double total=p.cal();
        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        float total1;
        total1 = Float.valueOf(decimalFormat.format(total));
        jLabel18.setText(String.valueOf(total1));
        double discount=p.cal2();
        DecimalFormat decimalFormat1 = new DecimalFormat("#.##");
        float discount2;
        discount2 = Float.valueOf(decimalFormat.format(discount));
        jTextField6.setText(String.valueOf(discount2));
        
        
        String code = jTextField1.getText();
        String itemName = jLabel13.getText();
        String quty = jTextField5.getText();
        String Discount = jTextField4.getText();
        String netamt = jLabel11.getText();
        
        String st []={code,itemName,quty,Discount,netamt};
        mod.addRow(st);
        
        String mrp=jLabel10.getText();
        String disAllowed=jLabel12.getText();
        String invoiceNo=jLabel9.getText();
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         try{
               
            String sql="SELECT c.Invoice_ID,c.Item_ID,c.Item_Name,c.QTY,c.MRP,c.DiscountsP,c.Discounts_Allowed,c.Net_Amount,r.Total,r.cash,r.changeA from creditsales c  INNER JOIN receipt r on c.Invoice_ID=r.InvoiceId where c.Invoice_ID="+jTextField3.getText()+"";
            pst=con.prepareStatement(sql);
           
            ResultSet rs = pst.executeQuery();
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            if(rs.next())
            {
                String total=rs.getString("Total");//get value
                jLabel18.setText(total);//set v//alue
                String cash=rs.getString("cash");
                jTextField2.setText(cash);
                String balance=rs.getString("ChangeA");
                jTextField6.setText(balance);
              //  String InvoiceId1=rs.getString("InvoiceId");
                //jLabel12.setText(InvoiceId1);
               jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }
        
         catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       Pay1 p2=new Pay1();
       p2.setTotal(Float.parseFloat(jLabel18.getText()));
       p2.setMony(Float.parseFloat(jTextField2.getText()));
       //p2.setMony(Float.parseFloat(jTextField9.getText()));
      
       double getBalance=p2.getBalance();
       //String pass=getText(balance); 
       DecimalFormat decimalFormat = new DecimalFormat("#.##");
        float total4;
        total4 = Float.valueOf(decimalFormat.format(getBalance));
       jTextField6.setText(String.valueOf(total4));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int r = jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        //assign data to variables
         String InvliceId = jTable1.getValueAt(r, 0).toString();
        String ItemCode = jTable1.getValueAt(r, 1).toString();
        String ItemName = jTable1.getValueAt(r, 2).toString();
        String Quantity = jTable1.getValueAt(r, 3).toString();
        String MRP = jTable1.getValueAt(r, 4).toString();
        String discountp = jTable1.getValueAt(r, 5).toString();
        String DiscountAllowed= jTable1.getValueAt(r, 6).toString();
        String netAmount= jTable1.getValueAt(r, 7).toString();
        String total=jTable1.getValueAt(r, 8).toString();
        String cash=jTable1.getValueAt(r, 9).toString();
        String balance=jTable1.getValueAt(r, 10).toString();
        //String price = jTable2.getValueAt(r, 4).toString();
        //assigning data to textfields and combo box
        jLabel9.setText(InvliceId);
        jTextField1.setText(ItemCode);
        jLabel13.setText(ItemName);
        jTextField5.setText(Quantity);
        jLabel10.setText(MRP);
        jTextField4.setText(discountp);
        jLabel12.setText(DiscountAllowed);
        jLabel11.setText(netAmount);
        jLabel18.setText(total);
        jTextField2.setText(cash);
        jTextField6.setText(balance);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       /* 
        Float saleAmount1;
        Float quty1;
        Float discount1;
        Float discunt;
        
        
        Pay1 p = new Pay1();
        p.setSaleAmount1(Float.parseFloat(jLabel10.getText()));
        p.setDiscount1(Float.parseFloat(jTextField4.getText()));
        p.setQuty1(Float.parseFloat(jTextField5.getText()));
        
        double total=p.cal();
        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        float total1;
        total1 = Float.valueOf(decimalFormat.format(total));
        jLabel18.setText(String.valueOf(total1));
        double discount=p.cal2();
        DecimalFormat decimalFormat1 = new DecimalFormat("#.##");
        float discount2;
        discount2 = Float.valueOf(decimalFormat.format(discount));
        jTextField2.setText(String.valueOf(discount2));
        */
        
         int Y = JOptionPane.showConfirmDialog(null, "Do You Want Update?");
          if(Y==0){
           //String billId=jTextField10.getText();
            String id=jTextField1.getText();
            String itemcode=jTextField1.getText();
            String name =jLabel13.getText();
            String quantity = jTextField5.getText();
            String discounte=jTextField4.getText();
            String salePrice=jLabel10.getText();
            String netPrice=jLabel13.getText();
            String date=jLabel16.getText();
            String discountAllowed=jLabel12.getText();
            
             String sql2="UPDATE creditsales SET  item_Code='"+itemcode+"',Item_Name='"+name+"',QTY="+quantity+",bill_Date='"+date+"',MRP="+salePrice+",DiscountsP="+ discounte+",Discounts_Allowed="+discountAllowed+",Net_Amount="+netPrice+"  where Invoice_ID="+id+" ";
             try
            {
            pst=con.prepareStatement(sql2);
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Updated");
            tableload();
          }
             
             catch(Exception e)
            {
            //JOptionPane.showMessageDialog(null, e);    
            e.printStackTrace();
            }
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int invoiceId=Integer.parseInt(jLabel9.getText());
        String code = jTextField1.getText();
        //int invoiceId = Integer.parseInt(jLabel12.getText());
        Float saleAmount = Float.parseFloat(jLabel10.getText());
        Float quty = Float.parseFloat(jTextField5.getText());
        Float discount = Float.parseFloat(jTextField4.getText());
        Float netamt = Float.parseFloat(jLabel11.getText());
        String itemName = jLabel13.getText();
        String date = jLabel17.getText();
        Float DisctAllowed=Float.parseFloat(jLabel12.getText());
        String time=jLabel16.getText();
        
        try {

            String qry = ("INSERT INTO bill (InvoiceId,item_Code,Item_Name,QTY,bill_Date,MRP,DiscountsP,Discounts_Allowed,Net_Amount,Time)VALUES("+invoiceId+",'" + code + "','" + itemName + "'," + quty + ",'"+date+"'," + saleAmount + "," + discount + "," + DisctAllowed + "," + netamt + ",'"+time+"')");
             pst = con.prepareStatement(qry);
                    //Statement pst=conn.createStatement();
            // tableload();
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added");

           
            
             
                    //Payment_2 p=new Payment_2();
           
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
            e.printStackTrace();
        }
       
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jLabel10.setText("");
        jTextField5.setText("");
        jTextField4.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
        jTextField3.setText("");
        jLabel9.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creditSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creditSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creditSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creditSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creditSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
