/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import DBConnect.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Loan extends javax.swing.JFrame {

    Connection con =null;
    PreparedStatement pst =null;
    ResultSet rs=null;
    /**
     * Creates new form Loan
     */
    public Loan() {
        initComponents();
         //connect to DB
        con =DBconnect.connect();
        
        //load table
        tableload();
        tableloadtt();
    }
    
    
        public void tableload()
    {
        try 
        {
       
        String sql="select l.Emp_ID,e.Emp_Name,l.Salary from loans l,employee e where e.Emp_ID=l.Emp_ID";
        pst=con.prepareStatement(sql);
        rs= pst.executeQuery();
        
        loan.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
        }
    }
        
          public void tableloadtt()
    {
        try 
        {
        
        String sql="select l.Emp_ID,e.Emp_Name,l.Salary,l.Loan_Type,l.Percentage_Allowed,l.Loan_Amount,l.Obtained_on,l.Duration from loans l,employee e where e.Emp_ID=l.Emp_ID";
        pst=con.prepareStatement(sql);
        rs= pst.executeQuery();
        
        tt.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
        }
    }
          
     private void clearfields()
     {
        
        ii.setText("");
        ss.setText("");
        loanamount.setText("");
        per.setText("");
        datebox.setDate(null);
        combo1.setSelectedIndex(0);;
        combo2.setSelectedIndex(0);;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        per = new javax.swing.JTextField();
        ii = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        ss = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        loanamount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datebox = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox();
        combo2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Calculate Loan");
        jButton1.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton1.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(211, 403, 140, 36);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Assign");
        jButton2.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton2.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton2.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(113, 602, 140, 36);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 79, 0, 0);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(113, 146, 45, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Percentage");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(113, 249, 93, 34);

        per.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                perKeyReleased(evt);
            }
        });
        getContentPane().add(per);
        per.setBounds(255, 250, 125, 34);
        getContentPane().add(ii);
        ii.setBounds(255, 146, 125, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("%");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(398, 256, 19, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Amount");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(113, 482, 80, 32);

        loan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Salary Level"
            }
        ));
        loan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(loan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(568, 146, 620, 228);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(113, 199, 67, 32);
        getContentPane().add(ss);
        ss.setBounds(255, 199, 125, 32);

        tt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tt);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(568, 482, 620, 253);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee Loans");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 35, 166, 44);

        loanamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loanamount.setText("calculated amount");
        getContentPane().add(loanamount);
        loanamount.setBounds(243, 482, 160, 32);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(113, 558, 56, 35);

        datebox.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(datebox);
        datebox.setBounds(243, 558, 160, 35);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Loan Type");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(113, 298, 93, 34);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton4.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton4.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1166, 39, 140, 36);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Duration");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(113, 351, 84, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Edit");
        jButton3.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton3.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton3.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(342, 602, 140, 36);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setText("Clear Fields");
        jButton5.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton5.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton5.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(225, 688, 140, 36);

        combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Loan Type", "Short-time Loan", "Long-time Loan" }));
        getContentPane().add(combo1);
        combo1.setBounds(255, 299, 125, 34);

        combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Duration", "1 week", "2 weeks", "3 weeks", " " }));
        getContentPane().add(combo2);
        combo2.setBounds(255, 351, 125, 25);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1370, 770);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanMouseClicked
        // mouse click
        int r=loan.getSelectedRow();
        String Id=loan.getValueAt(r, 0).toString();
        String sl=loan.getValueAt(r, 2).toString();
        
        ii.setText(Id);
        ss.setText(sl);
    }//GEN-LAST:event_loanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // assign data
        
        String Id=ii.getText();
        String i=loanamount.getText();
        String p=per.getText();
        String date;
        date = ((JTextField)datebox.getDateEditor().getUiComponent()).getText();
        String t1=combo1.getSelectedItem().toString();
        String t2=combo2.getSelectedItem().toString();
        
        if(!(per.getText().isEmpty()) && !(combo1.getSelectedItem().toString().isEmpty()) && !(combo2.getSelectedItem().toString().isEmpty()) && 
                !(((JTextField)datebox.getDateEditor().getUiComponent()).getText().isEmpty()))
        {
                       
        Loanclass x=new Loanclass();
        
        x.setId(Id);
        x.setAmount(Float.parseFloat(i));
        x.setPerc(Integer.parseInt(p));
        x.setDate(date);
        x.setLtype(t1);
        x.setDuration(t2);
       
        x.assign();
        //load table
        tableloadtt();
        clearfields();

        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select and enter all the required fields","Error",JOptionPane.ERROR_MESSAGE); 
            clearfields();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //claculate button
        if(!(per.getText().isEmpty()))
        {
                 
       Loanclass p = new Loanclass();
        
        p.setPerc(Integer.parseInt(per.getText()));
        p.setSalary(Float.parseFloat(ss.getText()));
        
        float l= p.calculate();
        loanamount.setText(String.valueOf(l));  
        }
        else
        {
        JOptionPane.showMessageDialog(this, "Please enter all the required fields","Error",JOptionPane.ERROR_MESSAGE); 
            clearfields();
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttMouseClicked
       try
       {     
        int r=tt.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tt.getModel();
        
        String Id=tt.getValueAt(r, 0).toString();
        String s=tt.getValueAt(r, 2).toString();
        String prc=tt.getValueAt(r, 4).toString();
        String lt=tt.getValueAt(r, 3).toString();
        String dur=tt.getValueAt(r, 7).toString();
        String amt=tt.getValueAt(r, 5).toString();
        Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(r, 6).toString());
        
        loanamount.setText(amt);
        combo2.setSelectedItem(dur);
        combo1.setSelectedItem(lt);
        per.setText(prc);
        datebox.setDate(date);
        ii.setText(Id);
        ss.setText(s);
       }
       catch(Exception e)
       {}
       
    }//GEN-LAST:event_ttMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HRM l=new HRM();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          // Update records
        
        int x=JOptionPane.showConfirmDialog(null,"Do you want to Update?");
       if(x==0)
       {
           
        String Id=ii.getText();
        String i=loanamount.getText();
        String p=per.getText();
        String date;
        date = ((JTextField)datebox.getDateEditor().getUiComponent()).getText();
        String t1=combo1.getSelectedItem().toString();
        String t2=combo2.getSelectedItem().toString();
         
        Loanclass y=new Loanclass();
        
        y.setId(Id);
        y.setAmount(Float.parseFloat(i));
        y.setPerc(Integer.parseInt(p));
        y.setDate(date);
        y.setLtype(t1);
        y.setDuration(t2);
       
        y.update();
           tableloadtt();
            clearfields();
    }  
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // clear fields
        clearfields();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void perKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perKeyReleased
        //   percentage
           String a=per.getText();
        int b=0;
        
       
        for(int i=0;i<a.length();i++)
        {
            if(!Character.isDigit(a.charAt(i)))
                b=1;    
        }
        
        if(b==1)
        {
            JOptionPane.showMessageDialog(null, "Enter a valid Integer");
            per.setText("");
        }
    }//GEN-LAST:event_perKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo1;
    private javax.swing.JComboBox combo2;
    private com.toedter.calendar.JDateChooser datebox;
    private javax.swing.JTextField ii;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable loan;
    private javax.swing.JLabel loanamount;
    private javax.swing.JTextField per;
    private javax.swing.JTextField ss;
    private javax.swing.JTable tt;
    // End of variables declaration//GEN-END:variables
}
