/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfa;

import DBConnect.DBconnect;
import Codes.ValidationChecker;
import controller.EquipmentController;
import controller.OtherResourcesController;
import controller.VehicleController;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Equipment;
import model.LeasedVehicle;
import model.OtherResources;
import model.Vehicle;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sandun
 */
public class AddResource extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form AddResource
     */
    public AddResource() {
        try {
            initComponents();
            con = DBconnect.connect();
            tableload();
            otable.setModel(DbUtils.resultSetToTableModel(VehicleController.getAllNormalVAsResultSet()));
            otherRTable.setModel(DbUtils.resultSetToTableModel(OtherResourcesController.getAllOtherResoucesAsResultSet()));
            leasedTable.setModel(DbUtils.resultSetToTableModel(VehicleController.getAllLeasedVAsResultSet()));
            eqtable.setModel(DbUtils.resultSetToTableModel(EquipmentController.getAllEqipmentAsResultSet()));
        } catch (SQLException ex) {
            Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void tableload() {
        try {
            String sql = "SELECT equi_id,equi_name,brand,serial,value FROM equipment";
    
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            eqtable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eqid = new javax.swing.JTextField();
        eqname = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        senum = new javax.swing.JTextField();
        val = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        eqtable = new javax.swing.JTable();
        addequpment = new javax.swing.JButton();
        editequpment = new javax.swing.JButton();
        deleteequpment = new javax.swing.JButton();
        cfequpment = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        aedate = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lvehid = new javax.swing.JTextField();
        lvehcom = new javax.swing.JTextField();
        lvehny = new javax.swing.JTextField();
        lvehinsche = new javax.swing.JComboBox<>();
        lvehinsfee = new javax.swing.JTextField();
        lvehinipay = new javax.swing.JTextField();
        lvehcost = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        leasedTable = new javax.swing.JTable();
        addleasedvehi = new javax.swing.JButton();
        editleasedvehi = new javax.swing.JButton();
        deleteleasedvehi = new javax.swing.JButton();
        cfleasedvehi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lvehtype = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        lvehnum = new javax.swing.JTextField();
        lvehlyear = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        lvehsdate = new com.toedter.calendar.JDateChooser();
        lvehedate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        otable = new javax.swing.JTable();
        cfownedveh = new javax.swing.JButton();
        arvdate = new com.toedter.calendar.JDateChooser();
        jLabel35 = new javax.swing.JLabel();
        ovehid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ovehtype = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ovehcost = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ovehnum = new javax.swing.JTextField();
        addownedveh = new javax.swing.JButton();
        updateownedveh = new javax.swing.JButton();
        deleteownedveh = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        orid = new javax.swing.JTextField();
        ortype = new javax.swing.JTextField();
        ordes = new javax.swing.JTextField();
        orval = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        otherRTable = new javax.swing.JTable();
        addotherr = new javax.swing.JButton();
        updateotherr = new javax.swing.JButton();
        deleteotherr = new javax.swing.JButton();
        cfotherr = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        oadate = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Equipment ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(24, 81, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Equipment Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(24, 144, 150, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Brand");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(24, 201, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Value");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(24, 339, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Serial Number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(24, 267, 130, 20);

        eqid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eqid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqidActionPerformed(evt);
            }
        });
        jPanel1.add(eqid);
        eqid.setBounds(174, 71, 180, 30);

        eqname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eqname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqnameActionPerformed(evt);
            }
        });
        jPanel1.add(eqname);
        eqname.setBounds(174, 134, 180, 30);

        brand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });
        jPanel1.add(brand);
        brand.setBounds(174, 191, 180, 30);

        senum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(senum);
        senum.setBounds(174, 257, 180, 30);

        val.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        val.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valKeyReleased(evt);
            }
        });
        jPanel1.add(val);
        val.setBounds(174, 326, 180, 30);

        eqtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Equipment ID", "Equipment Name", "Brand", "Serial Number", "Value", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eqtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eqtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eqtable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 70, 840, 411);

        addequpment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addequpment.setText("Add");
        addequpment.setMaximumSize(new java.awt.Dimension(130, 36));
        addequpment.setMinimumSize(new java.awt.Dimension(130, 36));
        addequpment.setPreferredSize(new java.awt.Dimension(130, 36));
        addequpment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addequpmentActionPerformed(evt);
            }
        });
        jPanel1.add(addequpment);
        addequpment.setBounds(24, 520, 132, 38);

        editequpment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editequpment.setText("Edit");
        editequpment.setMaximumSize(new java.awt.Dimension(130, 36));
        editequpment.setMinimumSize(new java.awt.Dimension(130, 36));
        editequpment.setPreferredSize(new java.awt.Dimension(130, 36));
        editequpment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editequpmentActionPerformed(evt);
            }
        });
        jPanel1.add(editequpment);
        editequpment.setBounds(174, 521, 130, 36);

        deleteequpment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteequpment.setText("Delete");
        deleteequpment.setMaximumSize(new java.awt.Dimension(130, 36));
        deleteequpment.setMinimumSize(new java.awt.Dimension(130, 36));
        deleteequpment.setPreferredSize(new java.awt.Dimension(130, 36));
        deleteequpment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteequpmentActionPerformed(evt);
            }
        });
        jPanel1.add(deleteequpment);
        deleteequpment.setBounds(314, 521, 130, 36);

        cfequpment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cfequpment.setText("Clear Fileds");
        cfequpment.setMaximumSize(new java.awt.Dimension(130, 36));
        cfequpment.setMinimumSize(new java.awt.Dimension(130, 36));
        cfequpment.setPreferredSize(new java.awt.Dimension(130, 36));
        cfequpment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfequpmentActionPerformed(evt);
            }
        });
        jPanel1.add(cfequpment);
        cfequpment.setBounds(462, 521, 130, 36);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Aquired Date");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(24, 407, 120, 20);

        aedate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(aedate);
        aedate.setBounds(174, 394, 180, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, 0, 1360, 610);

        jTabbedPane1.addTab("Equipments", jPanel1);

        jTabbedPane2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel6.setLayout(null);
        jPanel6.add(jLabel10);
        jLabel10.setBounds(22, 53, 0, 0);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setText("Vehicle ID");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(28, 22, 110, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setText("Leased company");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(28, 138, 160, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel26.setText("Start date");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(28, 179, 110, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel27.setText("End date");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(28, 217, 110, 20);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel28.setText("No: of years");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(28, 252, 130, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setText("Installment scheme");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(28, 290, 180, 20);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel30.setText("Installement fee");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(28, 328, 160, 20);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel31.setText("Initial payment");
        jPanel6.add(jLabel31);
        jLabel31.setBounds(28, 366, 150, 20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel32.setText("Total cost");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(28, 404, 110, 20);

        lvehid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel6.add(lvehid);
        lvehid.setBounds(191, 12, 150, 30);

        lvehcom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvehcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvehcomActionPerformed(evt);
            }
        });
        jPanel6.add(lvehcom);
        lvehcom.setBounds(191, 128, 150, 30);

        lvehny.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvehny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvehnyActionPerformed(evt);
            }
        });
        lvehny.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lvehnyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lvehnyKeyTyped(evt);
            }
        });
        jPanel6.add(lvehny);
        lvehny.setBounds(191, 242, 150, 30);

        lvehinsche.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lvehinsche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 months", "6months", "12 months" }));
        jPanel6.add(lvehinsche);
        lvehinsche.setBounds(191, 280, 150, 30);

        lvehinsfee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvehinsfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvehinsfeeActionPerformed(evt);
            }
        });
        lvehinsfee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lvehinsfeeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lvehinsfeeKeyTyped(evt);
            }
        });
        jPanel6.add(lvehinsfee);
        lvehinsfee.setBounds(191, 318, 150, 30);

        lvehinipay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvehinipay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvehinipayActionPerformed(evt);
            }
        });
        lvehinipay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lvehinipayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lvehinipayKeyTyped(evt);
            }
        });
        jPanel6.add(lvehinipay);
        lvehinipay.setBounds(191, 356, 150, 30);

        lvehcost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvehcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lvehcostKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lvehcostKeyTyped(evt);
            }
        });
        jPanel6.add(lvehcost);
        lvehcost.setBounds(191, 394, 150, 30);

        leasedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Leased Company", "Start date", "End date", "No: of years", "Installment fee", "Initial payment", "Total cost", "Special payments", "Fully paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        leasedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leasedTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(leasedTable);

        jPanel6.add(jScrollPane5);
        jScrollPane5.setBounds(370, 30, 970, 430);

        addleasedvehi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addleasedvehi.setText("Add");
        addleasedvehi.setMaximumSize(new java.awt.Dimension(130, 36));
        addleasedvehi.setMinimumSize(new java.awt.Dimension(130, 36));
        addleasedvehi.setPreferredSize(new java.awt.Dimension(130, 36));
        addleasedvehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addleasedvehiActionPerformed(evt);
            }
        });
        jPanel6.add(addleasedvehi);
        addleasedvehi.setBounds(30, 490, 130, 36);

        editleasedvehi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editleasedvehi.setText("Edit");
        editleasedvehi.setMaximumSize(new java.awt.Dimension(130, 36));
        editleasedvehi.setMinimumSize(new java.awt.Dimension(130, 36));
        editleasedvehi.setPreferredSize(new java.awt.Dimension(130, 36));
        editleasedvehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editleasedvehiActionPerformed(evt);
            }
        });
        jPanel6.add(editleasedvehi);
        editleasedvehi.setBounds(180, 490, 130, 36);

        deleteleasedvehi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteleasedvehi.setText("Delete");
        deleteleasedvehi.setMaximumSize(new java.awt.Dimension(130, 36));
        deleteleasedvehi.setMinimumSize(new java.awt.Dimension(130, 36));
        deleteleasedvehi.setPreferredSize(new java.awt.Dimension(130, 36));
        deleteleasedvehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteleasedvehiActionPerformed(evt);
            }
        });
        jPanel6.add(deleteleasedvehi);
        deleteleasedvehi.setBounds(340, 490, 130, 36);

        cfleasedvehi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cfleasedvehi.setText("Clear fields");
        cfleasedvehi.setMaximumSize(new java.awt.Dimension(130, 36));
        cfleasedvehi.setMinimumSize(new java.awt.Dimension(130, 36));
        cfleasedvehi.setPreferredSize(new java.awt.Dimension(130, 36));
        cfleasedvehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfleasedvehiActionPerformed(evt);
            }
        });
        jPanel6.add(cfleasedvehi);
        cfleasedvehi.setBounds(490, 490, 130, 36);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Type");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(28, 60, 80, 20);

        lvehtype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel6.add(lvehtype);
        lvehtype.setBounds(191, 52, 150, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel33.setText("Vehicle Number");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(28, 100, 150, 20);

        lvehnum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel6.add(lvehnum);
        lvehnum.setBounds(191, 90, 150, 30);

        lvehlyear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvehlyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvehlyearActionPerformed(evt);
            }
        });
        lvehlyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lvehlyearKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lvehlyearKeyTyped(evt);
            }
        });
        jPanel6.add(lvehlyear);
        lvehlyear.setBounds(191, 435, 150, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel34.setText("Leased year");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(28, 445, 160, 20);

        lvehsdate.setDateFormatString("yyyy-MM-dd");
        jPanel6.add(lvehsdate);
        lvehsdate.setBounds(191, 166, 150, 30);

        lvehedate.setDateFormatString("yyyy-MM-dd");
        jPanel6.add(lvehedate);
        lvehedate.setBounds(191, 204, 150, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jPanel6.add(jLabel21);
        jLabel21.setBounds(0, 0, 1360, 610);

        jTabbedPane2.addTab("Leased Vehicles", jPanel6);

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setLayout(null);

        otable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vehical ID", "Vehical Name", "Modal", "Year", "Vehical Number", "Aquired Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        otable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(otable);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(440, 60, 830, 402);

        cfownedveh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cfownedveh.setText("Clear Fields");
        cfownedveh.setMaximumSize(new java.awt.Dimension(130, 36));
        cfownedveh.setMinimumSize(new java.awt.Dimension(130, 36));
        cfownedveh.setPreferredSize(new java.awt.Dimension(130, 36));
        cfownedveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfownedvehActionPerformed(evt);
            }
        });
        jPanel4.add(cfownedveh);
        cfownedveh.setBounds(485, 487, 130, 36);

        arvdate.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(arvdate);
        arvdate.setBounds(170, 380, 160, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel35.setText("Aquired Date");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(30, 380, 120, 30);

        ovehid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ovehid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovehidActionPerformed(evt);
            }
        });
        jPanel4.add(ovehid);
        ovehid.setBounds(170, 90, 160, 28);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Vehical ID");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(24, 96, 110, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Vehical Type ");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(24, 171, 110, 20);

        ovehtype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(ovehtype);
        ovehtype.setBounds(170, 170, 160, 28);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Cost");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(33, 322, 50, 20);

        ovehcost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ovehcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovehcostActionPerformed(evt);
            }
        });
        ovehcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ovehcostKeyReleased(evt);
            }
        });
        jPanel4.add(ovehcost);
        ovehcost.setBounds(170, 320, 160, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Vehical Number");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(24, 243, 130, 20);

        ovehnum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(ovehnum);
        ovehnum.setBounds(170, 240, 160, 31);

        addownedveh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addownedveh.setText("Add");
        addownedveh.setMaximumSize(new java.awt.Dimension(130, 36));
        addownedveh.setMinimumSize(new java.awt.Dimension(130, 36));
        addownedveh.setPreferredSize(new java.awt.Dimension(130, 36));
        addownedveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addownedvehActionPerformed(evt);
            }
        });
        jPanel4.add(addownedveh);
        addownedveh.setBounds(59, 487, 130, 36);

        updateownedveh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateownedveh.setText("Edit");
        updateownedveh.setMaximumSize(new java.awt.Dimension(130, 36));
        updateownedveh.setMinimumSize(new java.awt.Dimension(130, 36));
        updateownedveh.setPreferredSize(new java.awt.Dimension(130, 36));
        updateownedveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateownedvehActionPerformed(evt);
            }
        });
        jPanel4.add(updateownedveh);
        updateownedveh.setBounds(197, 487, 130, 36);

        deleteownedveh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteownedveh.setText("Delete");
        deleteownedveh.setMaximumSize(new java.awt.Dimension(130, 36));
        deleteownedveh.setMinimumSize(new java.awt.Dimension(130, 36));
        deleteownedveh.setPreferredSize(new java.awt.Dimension(130, 36));
        deleteownedveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteownedvehActionPerformed(evt);
            }
        });
        jPanel4.add(deleteownedveh);
        deleteownedveh.setBounds(337, 487, 130, 36);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jPanel4.add(jLabel22);
        jLabel22.setBounds(0, 0, 1360, 610);

        jTabbedPane2.addTab("Owned Vehicles", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1428, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Motar Vehicles", jPanel2);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Resourse ID");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(51, 132, 110, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Type");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(51, 194, 50, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Description");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(51, 256, 100, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Value");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(51, 318, 50, 20);

        orid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oridActionPerformed(evt);
            }
        });
        jPanel3.add(orid);
        orid.setBounds(190, 120, 180, 30);

        ortype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(ortype);
        ortype.setBounds(190, 190, 180, 30);

        ordes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(ordes);
        ordes.setBounds(190, 250, 180, 30);

        orval.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orvalActionPerformed(evt);
            }
        });
        orval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                orvalKeyReleased(evt);
            }
        });
        jPanel3.add(orval);
        orval.setBounds(190, 310, 180, 30);

        otherRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Description", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        otherRTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otherRTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(otherRTable);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(490, 70, 792, 402);

        addotherr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addotherr.setText("Add");
        addotherr.setMaximumSize(new java.awt.Dimension(130, 36));
        addotherr.setMinimumSize(new java.awt.Dimension(130, 36));
        addotherr.setPreferredSize(new java.awt.Dimension(130, 36));
        addotherr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addotherrActionPerformed(evt);
            }
        });
        jPanel3.add(addotherr);
        addotherr.setBounds(51, 554, 130, 36);

        updateotherr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateotherr.setText("Edit");
        updateotherr.setMaximumSize(new java.awt.Dimension(130, 36));
        updateotherr.setMinimumSize(new java.awt.Dimension(130, 36));
        updateotherr.setPreferredSize(new java.awt.Dimension(130, 36));
        updateotherr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateotherrActionPerformed(evt);
            }
        });
        jPanel3.add(updateotherr);
        updateotherr.setBounds(207, 554, 130, 36);

        deleteotherr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteotherr.setText("Delete");
        deleteotherr.setMaximumSize(new java.awt.Dimension(130, 36));
        deleteotherr.setMinimumSize(new java.awt.Dimension(130, 36));
        deleteotherr.setPreferredSize(new java.awt.Dimension(130, 36));
        deleteotherr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteotherrActionPerformed(evt);
            }
        });
        jPanel3.add(deleteotherr);
        deleteotherr.setBounds(355, 554, 130, 36);

        cfotherr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cfotherr.setText("Clear Fields");
        cfotherr.setMaximumSize(new java.awt.Dimension(130, 36));
        cfotherr.setMinimumSize(new java.awt.Dimension(130, 36));
        cfotherr.setPreferredSize(new java.awt.Dimension(130, 36));
        cfotherr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfotherrActionPerformed(evt);
            }
        });
        jPanel3.add(cfotherr);
        cfotherr.setBounds(511, 554, 130, 36);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Aquired Date");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(51, 381, 110, 20);

        oadate.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(oadate);
        oadate.setBounds(190, 370, 180, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jPanel3.add(jLabel23);
        jLabel23.setBounds(0, 0, 1360, 610);

        jTabbedPane1.addTab("Land and Building", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 56, 1433, 712);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resources ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(747, 11, 110, 39);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1228, 21, 100, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eqidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eqidActionPerformed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandActionPerformed



    private void oridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oridActionPerformed

    private void ovehidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovehidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ovehidActionPerformed

    private void addequpmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addequpmentActionPerformed

//
        try {
            Equipment equipment = readEquipmentFields();
            int result = EquipmentController.addEquipment(equipment);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Equipment added successfully");
                clearEquipmentFields();
                eqtable.setModel(DbUtils.resultSetToTableModel(EquipmentController.getAllEqipmentAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Equipment cannot be added");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Equipment cannot be added");
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_addequpmentActionPerformed

    private void eqtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eqtableMouseClicked
        //mouse click event

        int r = eqtable.getSelectedRow();
        if (r != -1) {
            String id = eqtable.getValueAt(r, 0).toString();
            String name = eqtable.getValueAt(r, 1).toString();
            String bran = eqtable.getValueAt(r, 2).toString();
            String snum = eqtable.getValueAt(r, 3).toString();
            String value = eqtable.getValueAt(r, 4).toString();
            ((JTextField)aedate.getDateEditor().getUiComponent()).setText(eqtable.getValueAt(eqtable.getSelectedRow(), 5).toString());
            eqid.setText(id);
            eqname.setText(name);
            brand.setText(bran);
            senum.setText(snum);
            val.setText(value);

        }


    }//GEN-LAST:event_eqtableMouseClicked

    private void cfotherrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfotherrActionPerformed
        clearOtherResourceFields();
    }//GEN-LAST:event_cfotherrActionPerformed

    private void addownedvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addownedvehActionPerformed
        try {
            Vehicle vehicle = readOwnedTextValues();
            int result = VehicleController.addNormalVehicle(vehicle);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Vehicle added successfully");
                clearOwnedVfields();
                otable.setModel(DbUtils.resultSetToTableModel(VehicleController.getAllNormalVAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot add the vehicle");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addownedvehActionPerformed

    private void otableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otableMouseClicked
        if (otable.getSelectedRowCount() == 1) {
            ovehid.setText(otable.getValueAt(otable.getSelectedRow(), 0).toString());
            ovehtype.setText(otable.getValueAt(otable.getSelectedRow(), 1).toString());
            ovehnum.setText(otable.getValueAt(otable.getSelectedRow(), 2).toString());
            ovehcost.setText(otable.getValueAt(otable.getSelectedRow(), 3).toString());
            ((JTextField)arvdate.getDateEditor().getUiComponent()).setText(otable.getValueAt(otable.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_otableMouseClicked

    private void updateownedvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateownedvehActionPerformed
        try {
            Vehicle vehicle = readOwnedTextValues();
            int result = VehicleController.updateNormalVehicle(vehicle);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Vehicle updated successfully");
                clearOwnedVfields();
                otable.setModel(DbUtils.resultSetToTableModel(VehicleController.getAllNormalVAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot update the vehicle");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateownedvehActionPerformed

    private void deleteownedvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteownedvehActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            try {
                Vehicle vehicle = readOwnedTextValues();
                int result = VehicleController.deleteNormalVehicle(vehicle);
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Vehicle deleted successfully");
                    clearOwnedVfields();
                    otable.setModel(DbUtils.resultSetToTableModel(VehicleController.getAllNormalVAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot delete the vehicle");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteownedvehActionPerformed

    private void addotherrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addotherrActionPerformed
        try {
            OtherResources otherResources = readOtherResourceFields();
            int result = OtherResourcesController.addOtherResources(otherResources);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, " added successfully");
                clearOtherResourceFields();
                otherRTable.setModel(DbUtils.resultSetToTableModel(OtherResourcesController.getAllOtherResoucesAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be added ");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be added ");
            Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addotherrActionPerformed

    private void updateotherrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateotherrActionPerformed
        try {
            OtherResources otherResources = readOtherResourceFields();
            int result = OtherResourcesController.updateOtherResources(otherResources);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, " updated successfully");
                clearOtherResourceFields();
                otherRTable.setModel(DbUtils.resultSetToTableModel(OtherResourcesController.getAllOtherResoucesAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot update ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateotherrActionPerformed

    private void deleteotherrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteotherrActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            try {
                OtherResources otherResources = new OtherResources();
                otherResources.setResource_ID(orid.getText());
                int result = OtherResourcesController.deleteOtherResources(otherResources);
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, " delete successfully");
                    clearOtherResourceFields();
                    otherRTable.setModel(DbUtils.resultSetToTableModel(OtherResourcesController.getAllOtherResoucesAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot delete ");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteotherrActionPerformed

    private void otherRTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherRTableMouseClicked
        if (otherRTable.getSelectedRowCount() == 1) {

            orid.setText(otherRTable.getValueAt(otherRTable.getSelectedRow(), 0).toString());
            ortype.setText(otherRTable.getValueAt(otherRTable.getSelectedRow(), 1).toString());
            ordes.setText(otherRTable.getValueAt(otherRTable.getSelectedRow(), 2).toString());
            orval.setText(otherRTable.getValueAt(otherRTable.getSelectedRow(), 3).toString());
            ((JTextField)oadate.getDateEditor().getUiComponent()).setText(otherRTable.getValueAt(otherRTable.getSelectedRow(), 4).toString());
           
//                 oadate.setDate(new Date(otherRTable.getValueAt(otherRTable.getSelectedRow(), 4).toString()));

        }
    }//GEN-LAST:event_otherRTableMouseClicked

    private void lvehlyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvehlyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvehlyearActionPerformed

    private void addleasedvehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addleasedvehiActionPerformed

        try {
            Vehicle vehicle = readLeasedTextValues();

            int result = VehicleController.addLeasedVehicle(vehicle);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, " added successfully");
                clearLeasedFields();
                leasedTable.setModel(DbUtils.resultSetToTableModel(VehicleController.getAllLeasedVAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot add ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addleasedvehiActionPerformed

    private void deleteleasedvehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteleasedvehiActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            try {
                Vehicle vehicle = new Vehicle();
                vehicle.setVehicle_ID(lvehid.getText());
                int result = VehicleController.deleteLeasedVehicle(vehicle);
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, " deleted successfully");
                    clearLeasedFields();
                    leasedTable.setModel(DbUtils.resultSetToTableModel(VehicleController.getAllLeasedVAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot delete ");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteleasedvehiActionPerformed

    private void leasedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leasedTableMouseClicked
        if (leasedTable.getSelectedRowCount() == 1) {

            lvehid.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 0).toString());
            lvehtype.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 1).toString());
            lvehnum.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 2).toString());
            lvehcost.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 3).toString());
            lvehinipay.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 4).toString());
            lvehinsfee.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 5).toString());
            lvehcom.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 6).toString());
            lvehinsche.setSelectedItem(leasedTable.getValueAt(leasedTable.getSelectedRow(), 7).toString());
            lvehny.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 8).toString());
            ((JTextField)lvehsdate.getDateEditor().getUiComponent()).setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 9).toString());
            ((JTextField)lvehedate.getDateEditor().getUiComponent()).setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 10).toString());
            lvehlyear.setText(leasedTable.getValueAt(leasedTable.getSelectedRow(), 11).toString());
//                 oadate.setDateFormatString("yyyy-MM-dd");
//                 oadate.setDate(new Date(otherRTable.getValueAt(otherRTable.getSelectedRow(), 4).toString()));

        }
    }//GEN-LAST:event_leasedTableMouseClicked

    private void editleasedvehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editleasedvehiActionPerformed
        try {
            Vehicle vehicle = readLeasedTextValues();

            int result = VehicleController.updateLeasedVehicle(vehicle);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, " updated successfully");
                clearLeasedFields();
                leasedTable.setModel(DbUtils.resultSetToTableModel(VehicleController.getAllLeasedVAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot update ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddResource.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editleasedvehiActionPerformed

    private void cfownedvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfownedvehActionPerformed
        clearOwnedVfields();
    }//GEN-LAST:event_cfownedvehActionPerformed

    private void editequpmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editequpmentActionPerformed
        try {
            Equipment equipment = readEquipmentFields();
            int result = EquipmentController.updateEquipment(equipment);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Equipment updated");
                clearEquipmentFields();
                eqtable.setModel(DbUtils.resultSetToTableModel(EquipmentController.getAllEqipmentAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Equipment cannot update");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Equipment cannot  update");
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editequpmentActionPerformed

    private void deleteequpmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteequpmentActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            try {
                Equipment equipment = readEquipmentFields();
                int result = EquipmentController.deleteEquipment(equipment);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Equipment deleted");
                    clearEquipmentFields();
                    eqtable.setModel(DbUtils.resultSetToTableModel(EquipmentController.getAllEqipmentAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Equipment cannot delete");

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Equipment cannot  delete");
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteequpmentActionPerformed

    private void cfequpmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfequpmentActionPerformed
       clearEquipmentFields();
    }//GEN-LAST:event_cfequpmentActionPerformed

    private void cfleasedvehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfleasedvehiActionPerformed
       clearLeasedFields();
    }//GEN-LAST:event_cfleasedvehiActionPerformed

    private void valKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valKeyReleased
        if(!ValidationChecker.isInteger(val.getText()) && !val.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter only whole numbers");
        }
    }//GEN-LAST:event_valKeyReleased

    private void lvehnyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehnyKeyTyped
        
    }//GEN-LAST:event_lvehnyKeyTyped

    private void lvehinsfeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehinsfeeKeyTyped
       
    }//GEN-LAST:event_lvehinsfeeKeyTyped

    private void lvehinipayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvehinipayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvehinipayActionPerformed

    private void lvehinipayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehinipayKeyTyped
        
    }//GEN-LAST:event_lvehinipayKeyTyped

    private void lvehcostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehcostKeyTyped
         
    }//GEN-LAST:event_lvehcostKeyTyped

    private void lvehlyearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehlyearKeyTyped
         
    }//GEN-LAST:event_lvehlyearKeyTyped

    private void ovehcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovehcostActionPerformed
        
    }//GEN-LAST:event_ovehcostActionPerformed

    private void orvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orvalActionPerformed
        
    }//GEN-LAST:event_orvalActionPerformed

    private void lvehnyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehnyKeyReleased
        if(!ValidationChecker.isInteger(lvehny.getText()) && !lvehny.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter only whole numbers");
        }
    }//GEN-LAST:event_lvehnyKeyReleased

    private void lvehinsfeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehinsfeeKeyReleased
        if(!ValidationChecker.isDecimal(lvehinsfee.getText()) && !lvehinsfee.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter only numbers");
        }
    }//GEN-LAST:event_lvehinsfeeKeyReleased

    private void lvehinipayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehinipayKeyReleased
        if(!ValidationChecker.isDecimal(lvehinipay.getText()) && !lvehinipay.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter only numbers");
        }
    }//GEN-LAST:event_lvehinipayKeyReleased

    private void lvehcostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehcostKeyReleased
        if(!ValidationChecker.isDecimal(lvehcost.getText()) && !lvehcost.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter only numbers");
        }
    }//GEN-LAST:event_lvehcostKeyReleased

    private void lvehlyearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvehlyearKeyReleased
        if(!ValidationChecker.isYear(lvehlyear.getText()) && !lvehlyear.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid year");
        }
    }//GEN-LAST:event_lvehlyearKeyReleased

    private void ovehcostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ovehcostKeyReleased
        if(!ValidationChecker.isInteger(ovehcost.getText()) && !ovehcost.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter only whole numbers");
        }
    }//GEN-LAST:event_ovehcostKeyReleased

    private void orvalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orvalKeyReleased
        if(!ValidationChecker.isInteger(orval.getText()) && !orval.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter only whole numbers");
        }
    }//GEN-LAST:event_orvalKeyReleased

    private void eqnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eqnameActionPerformed

    private void lvehcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvehcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvehcomActionPerformed

    private void lvehnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvehnyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvehnyActionPerformed

    private void lvehinsfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvehinsfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvehinsfeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new RESource1().setVisible(true);
       this.dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddResource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addequpment;
    private javax.swing.JButton addleasedvehi;
    private javax.swing.JButton addotherr;
    private javax.swing.JButton addownedveh;
    private com.toedter.calendar.JDateChooser aedate;
    private com.toedter.calendar.JDateChooser arvdate;
    private javax.swing.JTextField brand;
    private javax.swing.JButton cfequpment;
    private javax.swing.JButton cfleasedvehi;
    private javax.swing.JButton cfotherr;
    private javax.swing.JButton cfownedveh;
    private javax.swing.JButton deleteequpment;
    private javax.swing.JButton deleteleasedvehi;
    private javax.swing.JButton deleteotherr;
    private javax.swing.JButton deleteownedveh;
    private javax.swing.JButton editequpment;
    private javax.swing.JButton editleasedvehi;
    private javax.swing.JTextField eqid;
    private javax.swing.JTextField eqname;
    private javax.swing.JTable eqtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable leasedTable;
    private javax.swing.JTextField lvehcom;
    private javax.swing.JTextField lvehcost;
    private com.toedter.calendar.JDateChooser lvehedate;
    private javax.swing.JTextField lvehid;
    private javax.swing.JTextField lvehinipay;
    private javax.swing.JComboBox<String> lvehinsche;
    private javax.swing.JTextField lvehinsfee;
    private javax.swing.JTextField lvehlyear;
    private javax.swing.JTextField lvehnum;
    private javax.swing.JTextField lvehny;
    private com.toedter.calendar.JDateChooser lvehsdate;
    private javax.swing.JTextField lvehtype;
    private com.toedter.calendar.JDateChooser oadate;
    private javax.swing.JTextField ordes;
    private javax.swing.JTextField orid;
    private javax.swing.JTextField ortype;
    private javax.swing.JTextField orval;
    private javax.swing.JTable otable;
    private javax.swing.JTable otherRTable;
    private javax.swing.JTextField ovehcost;
    private javax.swing.JTextField ovehid;
    private javax.swing.JTextField ovehnum;
    private javax.swing.JTextField ovehtype;
    private javax.swing.JTextField senum;
    private javax.swing.JButton updateotherr;
    private javax.swing.JButton updateownedveh;
    private javax.swing.JTextField val;
    // End of variables declaration//GEN-END:variables

    private Vehicle readOwnedTextValues() {
        String lid = ovehid.getText();
        String ltype = ovehtype.getText();
        String lnum = ovehnum.getText();
        Integer lcost = new Integer(ovehcost.getText());
        String vDate = ((JTextField)arvdate.getDateEditor().getUiComponent()).getText();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        Vehicle vehicle = new Vehicle(lid, ltype, lnum, lcost,vDate);

        return vehicle;
    }

    private void clearOwnedVfields() {
        ovehid.setText("");
        ovehtype.setText("");
        ovehnum.setText("");
        ovehcost.setText("");
        arvdate.setDate(null);
    }

    private OtherResources readOtherResourceFields() {

        String oid = orid.getText();
        String otype = ortype.getText();
        String odes = ordes.getText();
        Float orcost = new Float(orval.getText());
        String aquiredDate = ((JTextField)oadate.getDateEditor().getUiComponent()).getText();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        Date date = Calendar.getInstance().getTime();

        String lastUpdated = sdf.format(date);

        OtherResources otherResources = new OtherResources(oid, otype, odes, orcost, aquiredDate, lastUpdated);
        return otherResources;

    }

    private void clearOtherResourceFields() {
        orid.setText("");
        ortype.setText("");
        ordes.setText("");
        orval.setText("");
        oadate.setDate(null);
    }

    private Vehicle readLeasedTextValues() {
        String lid = lvehid.getText();
        String ltype = lvehtype.getText();
        String lnum = lvehnum.getText();
        Integer lcost = new Integer(lvehcost.getText());
        String lcom = lvehcom.getText();
        Float linipay = new Float(lvehinipay.getText());
        Float linsfee = new Float(lvehinsfee.getText());
        Integer nyears = new Integer(lvehny.getText());
        String vehiyear = lvehlyear.getText();
        String inscheme = lvehinsche.getSelectedItem().toString();
        String startdate = ((JTextField)lvehsdate.getDateEditor().getUiComponent()).getText();
        String enddate = ((JTextField)lvehedate.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        Vehicle vehicle = new Vehicle(lid, ltype, lnum, lcost,startdate);
        LeasedVehicle leasedVehicle = new LeasedVehicle(lid, linipay, linsfee, lcom, inscheme, nyears, startdate, enddate, vehiyear);
        vehicle.setLeasedVehicle(leasedVehicle);

        return vehicle;
    }

    private void clearLeasedFields() {
        lvehid.setText("");
        lvehtype.setText("");
        lvehnum.setText("");
        lvehcost.setText("");
        lvehcom.setText("");
        lvehinipay.setText("");
        lvehinsfee.setText("");
        lvehny.setText("");
        lvehlyear.setText("");
        lvehsdate.setDate(null);
        lvehedate.setDate(null);
    }

    private Equipment readEquipmentFields() {
        String id = eqid.getText();
        String name = eqname.getText();
        String br = brand.getText();
        String sr = senum.getText();
        Float va = new Float(val.getText());
        String edate = ((JTextField)aedate.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        Equipment equipment = new Equipment(id, name, br, sr, va,edate);
        return equipment;

    }

    private void clearEquipmentFields() {
        eqid.setText("");
        eqname.setText("");
        brand.setText("");
        senum.setText("");
        val.setText("");
        aedate.setDate(null);
    }

}
