/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfa;

import Codes.Constants;
import Codes.ValidationChecker;
import bill.Payment;
import controller.CustomerController;
import controller.DeliveryController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sandun
 */
public class Delivery extends javax.swing.JFrame {

    private ButtonGroup paymentButtonGroup;
    private ButtonGroup statusButtonGroup;

    /**
     * Creates new form Delivery
     */
    public Delivery() {
        initComponents();
        statusButtonGroup = new ButtonGroup();
        statusButtonGroup.add(ddeli);
        statusButtonGroup.add(dpen);
        paymentButtonGroup = new ButtonGroup();
        paymentButtonGroup.add(ddaid);
        paymentButtonGroup.add(doncash);
        try {
            dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.getAllDeliveryResultSet()));
            dcustt.setModel(DbUtils.resultSetToTableModel(CustomerController.getAllCustomersAsResultSet()));
        } catch (SQLException ex) {
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    Delivery(String jxBrowser_Google_Maps) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Donedeleiver = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delivid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        daddress = new javax.swing.JTextArea();
        Mapdeliver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ddeli = new javax.swing.JRadioButton();
        dpen = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        ddaid = new javax.swing.JRadioButton();
        doncash = new javax.swing.JRadioButton();
        delevradd = new javax.swing.JButton();
        delevrupdate = new javax.swing.JButton();
        delevrdelete = new javax.swing.JButton();
        delevrcf = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dinvoiceid = new javax.swing.JTextField();
        dcustid = new javax.swing.JTextField();
        dsearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dlisttext = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        dcustt = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        dcustsearchtext = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        Donedeleiver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Donedeleiver.setText("Done");
        Donedeleiver.setMaximumSize(new java.awt.Dimension(130, 36));
        Donedeleiver.setMinimumSize(new java.awt.Dimension(130, 36));
        Donedeleiver.setPreferredSize(new java.awt.Dimension(130, 36));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Manage Customer Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(49, 169, 259, 40);

        dTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(520, 329, 764, 320);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delivery");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(740, 10, 100, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Delivery ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 71, 130, 20);

        delivid.setEditable(false);
        delivid.setBackground(new java.awt.Color(102, 153, 255));
        delivid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(delivid);
        delivid.setBounds(180, 61, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(26, 398, 110, 20);

        daddress.setColumns(20);
        daddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        daddress.setRows(5);
        jScrollPane2.setViewportView(daddress);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(180, 400, 210, 90);

        Mapdeliver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mapdeliver.setText("Map");
        Mapdeliver.setMaximumSize(new java.awt.Dimension(130, 36));
        Mapdeliver.setMinimumSize(new java.awt.Dimension(130, 36));
        Mapdeliver.setPreferredSize(new java.awt.Dimension(130, 36));
        Mapdeliver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapdeliverActionPerformed(evt);
            }
        });
        getContentPane().add(Mapdeliver);
        Mapdeliver.setBounds(150, 520, 130, 36);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Status");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 580, 100, 20);

        ddeli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddeli.setSelected(true);
        ddeli.setText("Deliverd");
        ddeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddeliActionPerformed(evt);
            }
        });
        getContentPane().add(ddeli);
        ddeli.setBounds(153, 576, 81, 25);

        dpen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dpen.setText("Pending");
        getContentPane().add(dpen);
        dpen.setBounds(236, 576, 81, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Payment");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 620, 120, 20);

        ddaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddaid.setSelected(true);
        ddaid.setText("Paid");
        getContentPane().add(ddaid);
        ddaid.setBounds(150, 620, 55, 25);

        doncash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doncash.setText("On cash delivery");
        doncash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doncashActionPerformed(evt);
            }
        });
        getContentPane().add(doncash);
        doncash.setBounds(230, 620, 137, 25);

        delevradd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        delevradd.setText("Add");
        delevradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevraddActionPerformed(evt);
            }
        });
        getContentPane().add(delevradd);
        delevradd.setBounds(130, 670, 100, 29);

        delevrupdate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        delevrupdate.setText("Update");
        delevrupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevrupdateActionPerformed(evt);
            }
        });
        getContentPane().add(delevrupdate);
        delevrupdate.setBounds(250, 670, 120, 29);

        delevrdelete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        delevrdelete.setText("Delete");
        delevrdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevrdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(delevrdelete);
        delevrdelete.setBounds(380, 670, 110, 29);

        delevrcf.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        delevrcf.setText("Clear Fields");
        delevrcf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevrcfActionPerformed(evt);
            }
        });
        getContentPane().add(delevrcf);
        delevrcf.setBounds(500, 670, 140, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Invoice ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(26, 241, 130, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Customer ID");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(26, 112, 150, 20);

        dinvoiceid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dinvoiceid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dinvoiceidKeyReleased(evt);
            }
        });
        getContentPane().add(dinvoiceid);
        dinvoiceid.setBounds(179, 231, 210, 30);

        dcustid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(dcustid);
        dcustid.setBounds(179, 102, 210, 30);

        dsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dsearchKeyReleased(evt);
            }
        });
        getContentPane().add(dsearch);
        dsearch.setBounds(750, 280, 261, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Search by Invoice Number");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(520, 291, 220, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Delivery List");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(26, 293, 140, 20);

        dlisttext.setColumns(20);
        dlisttext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dlisttext.setRows(5);
        jScrollPane3.setViewportView(dlisttext);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(181, 289, 210, 100);

        dcustt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dcustt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcusttMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(dcustt);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(520, 117, 764, 144);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Search Customer by Telephone Number");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(520, 79, 330, 20);

        dcustsearchtext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dcustsearchtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dcustsearchtextKeyTyped(evt);
            }
        });
        getContentPane().add(dcustsearchtext);
        dcustsearchtext.setBounds(860, 70, 220, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1200, 30, 100, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delevraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevraddActionPerformed
        try {
            model.Delivery delivery = readDeliveryFields();
            int result = DeliveryController.addDelivery(delivery);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "added successfully");
                clearDeliveryFields();
                dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.getAllDeliveryResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be added");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be added");
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_delevraddActionPerformed

    private void delevrupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevrupdateActionPerformed
        try {
            model.Delivery delivery = readDeliveryFields();
            int result = DeliveryController.updateDelivery(delivery);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "updated successfully");
                clearDeliveryFields();
                dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.getAllDeliveryResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be updated");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be updated");
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delevrupdateActionPerformed

    private void delevrdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevrdeleteActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            try {
                model.Delivery delivery = readDeliveryFields();
                int result = DeliveryController.deleteDelivery(delivery);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "deleted successfully");
                    clearDeliveryFields();
                    dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.getAllDeliveryResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be deleted");

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Cannot be deleted");
                Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_delevrdeleteActionPerformed

    private void delevrcfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevrcfActionPerformed
        clearDeliveryFields();
    }//GEN-LAST:event_delevrcfActionPerformed

    private void doncashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doncashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doncashActionPerformed

    private void ddeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddeliActionPerformed

    private void dTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dTableMouseClicked
        if (dTable.getSelectedRowCount() == 1) {

            delivid.setText(dTable.getValueAt(dTable.getSelectedRow(), 0).toString());
            dlisttext.setText(dTable.getValueAt(dTable.getSelectedRow(), 1).toString());
            if (dTable.getValueAt(dTable.getSelectedRow(), 2).toString().equals(Constants.DELIVERY_PAYMENT_PAID)) {
                ddaid.setSelected(true);
            } else {
                doncash.setSelected(true);

            }
            daddress.setText(dTable.getValueAt(dTable.getSelectedRow(), 3).toString());
            if (dTable.getValueAt(dTable.getSelectedRow(), 4).toString().equals(Constants.DELIVERY_STATUS_DELIVERED)) {
                delevradd.setSelected(true);
            } else {
                dpen.setSelected(true);

            }
            dinvoiceid.setText(dTable.getValueAt(dTable.getSelectedRow(), 5).toString());
            
            dcustid.setText(dTable.getValueAt(dTable.getSelectedRow(), 6).toString());
            

//               
//               
        }
    }//GEN-LAST:event_dTableMouseClicked

    private void dsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dsearchKeyReleased
        try {
            dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.searchDeliveryByInvoiceID(dsearch.getText())));
        } catch (SQLException ex) {
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dsearchKeyReleased

    private void dinvoiceidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinvoiceidKeyReleased
        if (!ValidationChecker.isInteger(dinvoiceid.getText()) && !dinvoiceid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter integers only");
        }
    }//GEN-LAST:event_dinvoiceidKeyReleased

    private void MapdeliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapdeliverActionPerformed

        try {

            String URL = "https://www.google.lk/maps?source=tldsi&hl=en";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_MapdeliverActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Customer cus = new Customer();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dcusttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcusttMouseClicked
        if (dcustt.getSelectedRowCount() == 1) {

            dcustid.setText(dcustt.getValueAt(dcustt.getSelectedRow(), 0).toString());
            daddress.setText(dcustt.getValueAt(dcustt.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_dcusttMouseClicked

    private void dcustsearchtextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcustsearchtextKeyTyped
       try {
                if (!dcustsearchtext.getText().isEmpty()) {
                    dcustt.setModel(DbUtils.resultSetToTableModel(CustomerController.searchCustomerByTele(dcustsearchtext.getText())));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            } 
    }//GEN-LAST:event_dcustsearchtextKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Payment pay = new Payment();
        pay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Delivery().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Donedeleiver;
    private javax.swing.JButton Mapdeliver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dTable;
    private javax.swing.JTextArea daddress;
    private javax.swing.JTextField dcustid;
    private javax.swing.JTextField dcustsearchtext;
    private javax.swing.JTable dcustt;
    private javax.swing.JRadioButton ddaid;
    private javax.swing.JRadioButton ddeli;
    private javax.swing.JButton delevradd;
    private javax.swing.JButton delevrcf;
    private javax.swing.JButton delevrdelete;
    private javax.swing.JButton delevrupdate;
    private javax.swing.JTextField delivid;
    private javax.swing.JTextField dinvoiceid;
    private javax.swing.JTextArea dlisttext;
    private javax.swing.JRadioButton doncash;
    private javax.swing.JRadioButton dpen;
    private javax.swing.JTextField dsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    private model.Delivery readDeliveryFields() {
        
        String dlist = dlisttext.getText();
        Integer invoiceId = new Integer(dinvoiceid.getText());
        Integer customer = new Integer(dcustid.getText());
        String address = daddress.getText();
        String status = ddeli.isSelected() ? Constants.DELIVERY_STATUS_DELIVERED : Constants.DELIVERY_STATUS_PENDING;
        String payment = ddaid.isSelected() ? Constants.DELIVERY_PAYMENT_PAID : Constants.DELIVERY_STATUS_ON_CASH;

        model.Delivery delivery = new model.Delivery(dlist, payment, address, status, invoiceId, customer);
        return delivery;
    }

    private void clearDeliveryFields() {

        delivid.setText("");
        dinvoiceid.setText("");
        dlisttext.setText("");
        dcustid.setText("");
        daddress.setText("");
        ddeli.setSelected(true);
        ddaid.setSelected(true);

    }
}
